// Generated by CoffeeScript 1.6.3
var PluginError, colors, defaults, log, testium, through, _ref;

defaults = require('lodash.defaults');

testium = require('testium');

through = require('through');

_ref = require('gulp-util'), PluginError = _ref.PluginError, log = _ref.log, colors = _ref.colors;

module.exports = function(opts) {
  var end, files, process;
  if (opts == null) {
    opts = {};
  }
  files = [];
  opts = defaults(opts, {
    applicationPort: 4000,
    screenshotDirectory: "" + __dirname,
    browser: 'phantomjs',
    appDirectory: "" + __dirname
  });
  process = function(file) {
    if (file.isStream()) {
      return this.emit('error', new PluginError('gulp-testium', 'Streaming not supported'));
    }
    return files.push(file.path);
  };
  end = function() {
    var done,
      _this = this;
    log('karma running for', colors.magenta(files.length), files.length === 1 && 'file...' || 'files...');
    done = function() {
      return _this.emit('end');
    };
    if (files.length === 0) {
      return done();
    }
    opts.tests = files;
    return testium.run(opts, function(err, exitCode) {
      if (exitCode > 0) {
        _this.emit('error', new PluginError('gulp-testium', 'Karma exited with errors'));
      }
      if (err) {
        _this.emit('error', err);
      }
      return done();
    });
  };
  return through(process, end);
};
